name: prophet-example
channels:
  - conda-forge
dependencies:
  - python=3.6
  - pip
  - pip:
    - mlflow>=1.20.0
    - Cython
    - convertdate
    - LunarCalendar
    - holidays
    - tqdm
    - cmdstanpy
    - setuptools-git
    - python-dateutil
    - pystan>=2.19.1.1
    - prophet>=1.0.1

